version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app:latest
    container_name: laravel_app
    restart: unless-stopped
    tty: false
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: your-production-key-here
      DB_HOST: db
      REDIS_HOST: redis
    working_dir: /var/www
    volumes:
      - .:/var/www:ro
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - redis
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secure_password
      MYSQL_ROOT_PASSWORD: secure_root_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
